aa: rand-m7-mstd0.5-inc1
amp: true
apex_amp: false
aug_repeats: 3
aug_splits: 0
batch_size: 36
bce-loss: true
bce-target-thresh: 0.2
bce_loss: false
bce_target_thresh: null
bn_eps: null
bn_momentum: null
bn_tf: false
channels-last: false
channels_last: false
checkpoint_hist: 10
clip_grad: null
clip_mode: norm
color_jitter: 0.4
cooldown_epochs: 10
crop_pct: 0.95
cutmix: 1.0
cutmix_minmax: null
data_dir: /data/imagenet1k
dataset: imagenet
decay_epochs: 30
decay_rate: 0.1
dim: 768
dist_bn: ''
drop: 0.0
drop_block: null
drop_connect: null
drop_path: 0.2
dvs_aug: false
dvs_trival_aug: false
epoch_repeats: 0.0
epochs: 300
eval_metric: top1
experiment: ''
gp: null
hflip: 0.5
img_size: 224
in_channels: 3
initial_checkpoint: ''
input_size: null
interpolation: bicubic
jsd: false
layer: 8
local_rank: 0
log_interval: 100
log_wandb: false
lr: 0.001
lr_cycle_limit: 1
lr_cycle_mul: 1.0
lr_noise: null
lr_noise_pct: 0.67
lr_noise_std: 1.0
mean:
- 0.485
- 0.456
- 0.406
min_lr: 2.0e-05
mixup: 0.2
mixup_mode: batch
mixup_off_epoch: 0
mixup_prob: 1.0
mixup_switch_prob: 0.5
mlp-ratio: 4
mlp_ratio: 4
model: sdt
model-ema: false
model-ema-decay: 0.9998
model_ema: false
model_ema_decay: 0.9998
model_ema_force_cpu: false
momentum: 0.9
native_amp: false
no_aug: false
no_prefetcher: false
no_resume_opt: false
num_classes: 1000
num_heads: 8
opt: lamb
opt_betas: null
opt_eps: null
output: ''
patch_size: null
patience_epochs: 10
pin_mem: false
pooling_stat: '1111'
pretrained: false
ratio:
- 0.75
- 1.3333333333333333
recount: 1
recovery_interval: 0
remode: const
reprob: 0.0
resplit: false
resume: ''
save_images: false
scale:
- 0.08
- 1.0
sched: cosine
seed: 42
smoothing: 0.1
spike_mode: lif
split_bn: false
start_epoch: null
std:
- 0.229
- 0.224
- 0.225
sync_bn: false
time_steps: 4
torchscript: false
train_interpolation: bicubic
train_split: train
tta: 0
use_conv_as_linear: true
use_multi_epochs_loader: false
val_batch_size: 36
val_split: validation
vflip: 0.0
warmup_epochs: 20
warmup_lr: 1.0e-05
weight_decay: 0.01
workers: 8
